"""
Contains all alignment algorithms, including:

1. Pairwise global sequence alignment using Needleman-Wunsch as an implementation.
2. Multiple Sequence Alignment (MSA) using progressive alignment for sub-optimal (but fast) results.
"""

import dataclasses
from collections import Counter
from enum import Enum

GAP = "-"


class Move(Enum):
    NONE = 0  # default uninitialized value
    UP = 1
    LEFT = 2
    DIAGONAL = 3


@dataclasses.dataclass(frozen=True)
class AlignmentResult:
    aligned_seq1: str
    aligned_seq2: str
    score: float
    score_matrix: list[list[float]] | None
    moves: list[Move] | None


class DistanceMatrix:
    def __init__(self, data: dict[tuple[int, int], AlignmentResult]):
        self._data = data
        self.n = len(data)

    def get(self, i: int, j: int) -> AlignmentResult:
        max_idx = self.n - 1

        if i > max_idx or j > max_idx:
            raise IndexError(f"Index i or j are out of bounds for size {self.n}")

        if i == j:
            raise ValueError("Self-alignment is not supported.")

        if i > j:
            i, j = j, i

        return self._data[i, j]


def align(seq1: str, seq2: str, alpha: int, no_store: bool = True) -> AlignmentResult:
    """
    Perform global sequence alignment using the Needleman-Wunsch algorithm.

    Parameters
    --------
    seq1 : str
        The first sequence of length ``m`` that will be aligned
    seq2 : str
        The second sequence of length ``n`` that will be aligned
    alpha : int
        Parameter that defines the penalties for gaps and mismatches.
        The higher the value, the more harsh the penalty is.
    no_store : bool, optional
        Flag to tell the algorithm to not store additional information such as
        the score matrix and move list. Setting this flag to ``True`` saves memory.
    """
    m = len(seq1)
    n = len(seq2)

    match_reward = 1
    gap_penalty = -alpha
    mismatch_penalty = -alpha / 2

    def s(a: str, b: str):
        if a == b:
            return match_reward
        else:
            return mismatch_penalty

    # scoring matrix
    dp: list[list[float]] = [[0] * (n + 1) for _ in range(m + 1)]

    # "best move" matrix. Based on the score matrix (AKA: traceback matrix)
    trace: list[list[Move]] = [[Move.NONE] * (n + 1) for _ in range(m + 1)]

    # Initialize first column boundary conditions: i * α
    for i in range(1, m + 1):
        dp[i][0] = i * gap_penalty
        trace[i][0] = Move.UP  # only way to go if you end up here

    # Initialize first row boundary conditions: j * α
    for j in range(1, n + 1):
        dp[0][j] = j * gap_penalty
        trace[0][j] = Move.LEFT  # only way to go if you end here

    # Main DP loop (Scoring Process)
    for i in range(1, m + 1):
        for j in range(1, n + 1):
            match = dp[i - 1][j - 1] + s(seq1[i - 1], seq2[j - 1])
            delete = dp[i - 1][j] + gap_penalty
            insert = dp[i][j - 1] + gap_penalty

            best = max(match, delete, insert)

            dp[i][j] = best

            if best == match:
                trace[i][j] = Move.DIAGONAL
            elif best == delete:
                trace[i][j] = Move.UP
            elif best == insert:
                trace[i][j] = Move.LEFT
            else:
                raise RuntimeError("Impossible branch hit")

    moves: list[Move] = []
    aligned1: list[str] = []
    aligned2: list[str] = []
    i = m
    j = n

    # Alignment Process
    while i > 0 or j > 0:
        move = trace[i][j]

        if not no_store:
            moves.append(move)

        if move == Move.DIAGONAL:  # (i-1, j-1) ancestor
            aligned1.append(seq1[i - 1])
            aligned2.append(seq2[j - 1])
            i -= 1
            j -= 1

        elif move == Move.UP:  # (i-1, j) ancestor
            aligned1.append(seq1[i - 1])
            aligned2.append(GAP)
            i -= 1

        elif move == Move.LEFT:  # (i, j-1) ancestor
            aligned1.append(GAP)
            aligned2.append(seq2[j - 1])
            j -= 1

        else:
            raise RuntimeError("Impossible branch hit.")

    return AlignmentResult(
        aligned_seq1="".join(aligned1[::-1]),
        aligned_seq2="".join(aligned2[::-1]),
        score=dp[m][n],
        score_matrix=None if no_store else dp,
        moves=None if no_store else moves[::-1],
    )


def _build_distance_matrix(sequences: list[str], alpha: int) -> DistanceMatrix:
    """
    Contains all pairwise global alignment scores for all the pairs of given sequences.

    This produces an optimal data structure that exploits the symmetric matrix generated by calculating
    global alignment per pair. If g(a, b) is the global alignment score function and A, B, and C are sequences,
    then the matrix is of the following form:

      |    A    |    B    |    C    |
    --|---------|---------|---------|
    A |    -    | g(A, B) | g(A, C) |
    B | g(B, A) |    -    | g(B, C) |
    C | g(C, A) | g(C, B) |    -    |

    Because by definition g(S1, S2) = g(S2, S1), the matrix is symmetric and we can save storage space.
    """

    n = len(sequences)
    scores: dict[tuple[int, int], AlignmentResult] = {}

    for i in range(n):
        # Triangular indexing to take only the upper triangular part of the matrix
        for j in range(i + 1, n):
            a = sequences[i]
            b = sequences[j]

            scores[(i, j)] = align(a, b, alpha=alpha, no_store=True)

    return DistanceMatrix(scores)


def _best_alignment_pair(distances: DistanceMatrix) -> tuple[int, int, AlignmentResult]:
    best_score = -1e10
    best = None

    for i in range(distances.n):
        for j in range(i + 1, distances.n):
            alignment = distances.get(i, j)
            score = alignment.score
            if score > best_score:
                best_score = score
                best = (i, j, alignment)

    if best is None:
        raise RuntimeError("Empty distance matrix provided")

    return best


def _build_consensus(sequences: list[str]) -> str:
    """
    Construct a 'consensus' sequence from two or more sequences. The consensus sequence essentially reflects
    the most common symbols for each position of the sequences.

    Example
    --------

    n | 0 | 1 | 2 | 3 | 4 | 5 | 6 |
    --|---|---|---|---|---|---|----
    A | A | G | T | C | C | A | A |
    B | A | - | T | G | C | - | A |
    C | G | - | A | C | G | A | C |
    X | A | G | T | C | C | A | A |

    In the table above, the consensus sequence is X = AGTCCAA, reflecting the most frequent symbols for each position/column.
    IMPORTANT: Note there are no gaps in the consensus, this is intentional.
    """
    if len(sequences) < 2:
        raise ValueError("A consensus can be determined for two or more sequences.")

    if len(set(len(x) for x in sequences)) > 1:
        raise ValueError("All sequences should have the same length!")

    symbols: list[str] = []

    for col in range(len(sequences[0])):
        column = [x[col] for x in sequences if x[col] != GAP]
        most_common_symbol = Counter(column).most_common(1)[0][0]
        symbols.append(most_common_symbol)

    return "".join(symbols)


def _pick_next_index(
    remaining: set[int],
    included: set[int],
    distances: DistanceMatrix,
) -> int:
    """
    Greedy nearest-neighbour strategy for advancing the MSA. This is nice and simple.
    """
    best_score = -1e10
    best_idx = -1

    for k in remaining:
        for m in included:
            score = distances.get(k, m).score
            if score > best_score:
                best_score = score
                best_idx = k

    return best_idx


def _add_gaps(sequences: list[str], aligned_consensus: str) -> list[str]:
    """
    Insert/propagate gaps from the aligned consensus into the list of MSA sequences.

    Motivation
    --------
    Pairwise aligning two sequences could result in them having a bigger length.
    This means that the newly aligned sequences will have a length mismatch with the older
    ones. This is absolutely not allowed, MSA strictly produces same-length sequences.

    """
    new_sequences: list[str] = []

    for seq in sequences:
        symbols: list[str] = []
        old_col = 0

        for x in aligned_consensus:
            if x == GAP:
                symbols.append(GAP)
            else:
                symbols.append(seq[old_col])
                old_col += 1

        new_sequences.append("".join(symbols))

    return new_sequences


def multiple_align(sequences: list[str], alpha: int) -> list[str]:
    """
    Align the list of given ``sequences``.
    """
    distances = _build_distance_matrix(sequences, alpha)

    i, j, first = _best_alignment_pair(distances)
    msa: dict[int, str] = {i: first.aligned_seq1, j: first.aligned_seq2}
    remaining = set(range(len(sequences))) - {i, j}

    while len(remaining) > 0:
        included = set(msa.keys())
        msa_sequences = list(msa.values())

        next_idx = _pick_next_index(remaining, included, distances)
        consensus = _build_consensus(msa_sequences)
        result = align(consensus, sequences[next_idx], alpha=alpha)
        updated = _add_gaps(msa_sequences, result.aligned_seq1)

        msa = dict(zip(included, updated))
        msa[next_idx] = result.aligned_seq2

        remaining.remove(next_idx)

    return [msa[i] for i in range(len(msa))]


# Small demo program to play with the algorithms
if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest="command")

    pairwise_parser = subparsers.add_parser("pairwise-align")

    pairwise_parser.add_argument("seq1", type=str)
    pairwise_parser.add_argument("seq2", type=str)
    pairwise_parser.add_argument("id", type=int)

    multi_parser = subparsers.add_parser("multi-align")

    multi_parser.add_argument("seqs", nargs="+", type=str)
    multi_parser.add_argument("--id", type=int, required=True)

    args = parser.parse_args()

    alpha = 2 - args.id % 2

    if args.command == "pairwise-align":
        print(f"α = {alpha}")
        print(f"A = {args.seq1}")
        print(f"B = {args.seq2}")

        result = align(args.seq1, args.seq2, alpha)

        print("\nAlignment\n--------")
        print(result.aligned_seq1)
        print(result.aligned_seq2)

    if args.command == "multi-align":
        print(f"α = {alpha}")
        for i, s in enumerate(args.seqs):
            print(f"s{i} = {s}")

        result = multiple_align(args.seqs, alpha=alpha)

        print("\nAlignment\n--------")
        for s in result:
            print(s)
